import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { verifyChain } from '@/lib/audit';
import crypto from 'crypto';

// Generates a signed PDF case-bundle as a downloadable text-based PDF (simplified for demo)
// Real implementation would use pdfkit; here we produce a minimal valid PDF.
export async function GET(_req: NextRequest, { params }: { params: Promise<{ caseId: string }> }) {
  const { caseId } = await params;
  const caseRecord = await db.case.findFirst({
    where: { OR: [{ id: caseId }, { caseId }] },
    include: {
      work: {
        include: {
          vendor: true,
          payments: { orderBy: { paidAt: 'asc' } },
          riskScores: { take: 1, orderBy: { scoredAt: 'desc' } },
          state: true,
          district: true,
        },
      },
      auditLog: { orderBy: { timestamp: 'asc' } },
    },
  });

  if (!caseRecord) return NextResponse.json({ error: 'Case not found' }, { status: 404 });

  const verification = await verifyChain(caseRecord.id);
  const bundle = buildCaseBundle(caseRecord, verification);
  const pdfBytes = generateSimplePdf(bundle);
  const signature = crypto.createHash('sha256').update(bundle).digest('hex');

  return new NextResponse(pdfBytes, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${caseRecord.caseId}-case-bundle.pdf"`,
      'X-Signature': signature,
      'X-Signature-Algorithm': 'SHA-256',
      'X-Timestamp': new Date().toISOString(),
    },
  });
}

function buildCaseBundle(caseRecord: any, verification: any): string {
  const lines: string[] = [];
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('  MPLAD SENTINEL — CASE BUNDLE');
  lines.push('  Prepared for legal/audit handoff');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  lines.push(`Case ID: ${caseRecord.caseId}`);
  lines.push(`Status: ${caseRecord.status}`);
  lines.push(`Priority: ${caseRecord.priority}`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('──────────── WORK DETAILS ────────────');
  const w = caseRecord.work;
  lines.push(`Work ID: ${w.workId}`);
  lines.push(`Title: ${w.title}`);
  lines.push(`Description: ${w.description}`);
  lines.push(`Category: ${w.category}`);
  lines.push(`Fund Sanctioned: ₹${w.fundSanctioned} L`);
  lines.push(`Fund Utilized: ₹${w.fundUtilized} L`);
  lines.push(`Status: ${w.status}`);
  lines.push(`State: ${w.state?.name || '—'}`);
  lines.push(`District: ${w.district?.name || '—'}`);
  lines.push('');
  lines.push('──────────── VENDOR ────────────');
  lines.push(`Vendor ID: ${w.vendor?.vendorId || '—'}`);
  lines.push(`Vendor Name: ${w.vendor?.name || '—'}`);
  lines.push(`PAN (masked): ${w.vendor ? w.vendor.pan.substring(0, 3) + 'XXXXX' + w.vendor.pan.substring(8) : '—'}`);
  lines.push('');
  lines.push('──────────── RISK ASSESSMENT ────────────');
  const r = w.riskScores[0];
  if (r) {
    lines.push(`Risk Tier: ${r.riskTier.toUpperCase()}`);
    lines.push(`Ensemble Score: ${(r.ensembleScore * 100).toFixed(1)}%`);
    lines.push(`Blacklist Match: ${r.blacklistMatch ? 'YES' : 'No'}`);
    lines.push(`Rule Flags: ${JSON.parse(r.ruleFlags || '[]').map((f: any) => f.label).join(', ') || '—'}`);
    lines.push(`SHAP Top Features:`);
    const shap = JSON.parse(r.shapJson || '[]');
    shap.slice(0, 5).forEach((s: any) => {
      lines.push(`  • ${s.feature}: contribution=${(s.contribution * 100).toFixed(1)}% (${s.direction})`);
    });
  }
  lines.push('');
  lines.push('──────────── PAYMENT TIMELINE ────────────');
  w.payments.forEach((p: any) => {
    lines.push(`  ${p.paidAt.toISOString().substring(0, 10)}  ₹${(p.amount * 100000).toFixed(0)}  via ${p.instrument}  (ref: ${p.reference})`);
  });
  lines.push('');
  lines.push('──────────── AUDIT TRAIL ────────────');
  lines.push(`Chain Valid: ${verification.valid ? 'YES — chain is intact' : 'NO — chain has been tampered'}`);
  if (verification.brokenAt) lines.push(`Broken at entry: ${verification.brokenAt}`);
  verification.entries.forEach((e: any, i: number) => {
    lines.push(`  ${i + 1}. [${e.timestamp.substring(0, 19)}] ${e.action} (by ${e.actorName})`);
    lines.push(`     hash: ${e.thisHash.substring(0, 16)}...  valid: ${e.valid ? '✓' : '✗'}`);
  });
  lines.push('');
  lines.push('──────────── SIGNATURE ────────────');
  lines.push(`Bundle SHA-256: ${crypto.createHash('sha256').update('placeholder').digest('hex')}`);
  lines.push(`Timestamp: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('This document is generated by MPLAD Sentinel for SIH26102.');
  lines.push('All data is synthetic for demonstration purposes.');
  return lines.join('\n');
}

// Generate a minimal valid PDF from text content
function generateSimplePdf(text: string): Uint8Array {
  const lines = text.split('\n');
  const pdfLines: string[] = [];
  pdfLines.push('%PDF-1.4');
  pdfLines.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj');
  pdfLines.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj');
  pdfLines.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj');

  // Content stream — render each line
  let y = 760;
  let content = 'BT /F1 9 Tf\n';
  for (const line of lines) {
    // Escape parentheses
    const safe = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    content += `1 0 0 1 50 ${y} Tm (${safe}) Tj\n`;
    y -= 11;
    if (y < 40) {
      // Would page-break in real PDF; here we just stop
      break;
    }
  }
  content += 'ET';
  pdfLines.push(`4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj`);
  pdfLines.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj');

  // xref table — basic
  const objs: { offset: number; num: number }[] = [];
  let pos = 0;
  const parts: string[] = [];
  for (let i = 0; i < pdfLines.length; i++) {
    const line = pdfLines[i];
    const num = i + 1;
    objs.push({ offset: pos, num });
    parts.push(line);
    pos += line.length + 1; // +1 for newline
  }
  const xrefStart = pos;
  let xref = 'xref\n0 ' + (objs.length + 1) + '\n0000000000 65535 f \n';
  for (const obj of objs) {
    xref += String(obj.offset).padStart(10, '0') + ' 00000 n \n';
  }
  parts.push(xref);
  parts.push(`trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`);

  const fullPdf = parts.join('\n');
  return new TextEncoder().encode(fullPdf);
}
